<?php $session = $this->session->userdata('user_session'); ?>
<h4><?php echo $messages_data[0]->subject; ?></h4>
<?php foreach ($messages_data as $message) { ?>
<div class="panel panel-transparent panel-square">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a class="block-collapse" data-toggle="collapse" href="<?php echo '#read-mail-' . $message->id; ?>">
             <img src="<?php echo IMG_URL . 'user_avtar/40X40/' . $message->from_avtar; ?>" class="avatar img-circle" alt="Avatar"> 
             <?php if ($session->id != $message->from_id) { ?>
             <strong><?php echo $message->from_person; ?></strong>
             <?php
         } else {
            echo 'Me';
        }
        ?>
        <span>&nbsp;to&nbsp;</span> 
        <?php if ($message->type == 'single' && $session->id != $message->to_id) { ?>

        <img src="<?php echo IMG_URL . 'user_avtar/40X40/' . $message->to_avtar; ?>" class="avatar img-circle" alt="Avatar"> 
        <strong><?php echo $message->to_person; ?></strong>
        <?php
    } else {
       if ($message->type == 'single'){
        echo 'Me';
    }else if ($message->type == 'group'){
        $group = explode('_', $message->group_id);
        echo '<span class="label label-warning">' ,ucwords($group[0]) , ' group</span>';
    }
}
?>
<span class="right-content">
    <span class="time"><?php echo time_elapsed_string($message->timestamp); ?></span>
</span>
</a>
</h3>
</div>
<div id="<?php echo 'read-mail-' . $message->id; ?>" class="collapse">
    <div class="panel-body">
        <?php echo $message->message; ?>
    </div>

    <?php if(messageHasAttachments($message->id)){ ?>
    <div class="panel-footer">
        <p><strong><?php echo $this->lang->line('attachmments'); ?>  :</strong></p>
        <ul class="attachment-list">
        <?php
            foreach (getMessageAttachments($message->id) as $value) {
               echo '<li><a href="'.base_url() .'message/attachmment/download/'. $value->id .'">'.$value->original_name.'</a> - <small>'.$value->file_size.' Kb</small></li>';
            }
        ?>
        </ul>
    </div>
    <?php } ?>
</div>
</div>
<?php } ?>

<div class="clear">&nbsp;</div>
<?php $session = $this->session->userdata('user_session'); ?>
<script>
    //<![CDATA[
    $(document).ready(function() {
        function validateEditor() {
            $('#compose_message').bootstrapValidator('revalidateField', 'message');
        };
        
        $('#compose_message').bootstrapValidator({
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'fa fa-times',
                validating: 'glyphicon glyphicon-refresh'
            },

            fields: {
                'to_id[]': {
                    validators: {
                        notEmpty: {
                            message: 'The to  is required'
                        }
                    }
                },
                'subject': {
                    validators: {
                        notEmpty: {
                            message: 'The subject is required'
                        }
                    }
                },
                'message': {
                    validators: {
                        callback: {
                            message: 'The message is required and cannot be empty',
                            callback: function(value, validator) {
                                var code = $('[name="message"]').code();
                                // <p><br></p> is code generated by Summernote for empty content
                                return (code !== '' && code !== '<p><br></p>');
                            }
                        }
                    }
                },
                'attachments[]': {
                validators: {
                    file: {
                        extension: 'jpg,png,jpeg',
                        message: 'The selected file is not valid'
                    }
                }
            }
            }
        }).on('click', '.addButton', function() {
            $(this).parent().find('.removeButton').show();
            $(this).parent().find('.addButton').hide();
            var $template = $('#optiontemplate'),
                $clone    = $template
                                .clone()
                                .removeClass('hide')
                                .removeAttr('id')
                                .insertBefore($template),
                $option   = $clone.find('[name="attachments[]"]');
            $('#compose_message').bootstrapValidator('addField', $option);
        }).on('click', '.removeButton', function() {
            $(this).parent().parent().prev().find('.removeButton').hide();
            $(this).parent().parent().prev().find('.addButton').show();
            var $row    = $(this).parents('.form-group'),
                $option = $row.find('[name="attachments[]"]');
            $row.remove();
            $('#compose_message').bootstrapValidator('removeField', $option);
        }) .on('success.validator.bv', function(e, data) {
            $(data.element[0]).parent().parent().find('.addButton').show();
            $(data.element[0]).parent().parent().find('.removeButton').hide();   
        }).on('error.validator.bv', function(e, data) {
            $(data.element[0]).parent().parent().find('.removeButton').show(); 
            $(data.element[0]).parent().parent().find('.addButton').hide();   
        }).find('[name="message"]').summernote({
            height: 200,
            onkeyup: function() {
                validateEditor();
            },
            onpaste: function() {
                validateEditor();
            }
        });
     });
    //]]>
</script>
    <form role="form" action="<?php echo base_url() . 'message/reply/' . $to_reply_data->id; ?>" method="post" enctype="multipart/form-data" id="compose_message" class="form-horizontal">
        <div class="col-sm-12">
            <div class="form-group">
                <textarea class="summernote-sm" name="message" data-bv-excluded="false"><?php echo set_value('message'); ?></textarea>
                <?php if (form_error('message') != '') { ?>
                <label class="error"><?php echo form_error('message'); ?></label>
                <?php } ?>
            </div>

            <div class="form-group">
            <div class="col-lg-10 padding-killer">
                <input type="file" name="attachments[]" class="form-control">
            </div>
            <div class="col-lg-2 pull-right">
                <button type="button" class="btn btn-primary addButton" style="display:none">
                    <i class="fa fa-plus"></i>
                </button>

                <button type="button" class="btn btn-primary removeButton" style="display:none">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>

        <div class="form-group hide" id="optiontemplate">
            <div class="col-lg-10 padding-killer">
                <input type="file" name="attachments[]" class="form-control">
            </div>
            <div class="col-lg-2 pull-right">
                <button type="button" class="btn btn-primary addButton" style="display:none">
                    <i class="fa fa-plus"></i>
                </button>

                <button type="button" class="btn btn-primary removeButton" style="display:none">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>

            <div class="form-group">
                <button type="submit" name="action" value="send" class="btn btn-success" data-toggle="tooltip" title="<?php echo $this->lang->line('send'), ' ', $this->lang->line('message'); ?>"><i class="fa fa-rocket"></i> <?php echo $this->lang->line('send'), ' ', $this->lang->line('message'); ?></button>
                <a href="<?php echo base_url() . 'message'; ?>" class="btn btn-danger" data-toggle="tooltip" title="<?php echo $this->lang->line('discard'); ?>"><?php echo $this->lang->line('discard'); ?></a>
            </div>
        </div>
    </form>