<h4><?php echo $messages_data[0]->subject; ?></h4>
<?php foreach ($messages_data as $message) { ?>
    <div class="panel panel-transparent panel-square">
        <div class="panel-heading">
            <h3 class="panel-title">
                <a class="block-collapse" data-toggle="collapse" href="<?php echo '#read-mail-' . $message->id; ?>">
                    <img src="<?php echo IMG_URL . 'user_avtar/40X40/' . $message->avtar; ?>" class="avatar img-circle" alt="Avatar"> 
                    <strong><?php echo $message->sender; ?></strong> to me
                    <span class="right-content">
                        <span class="time"><?php echo time_elapsed_string($message->timestamp); ?></span>
                    </span>
                </a>
            </h3>
        </div>
        <div id="<?php echo 'read-mail-' . $message->id; ?>" class="collapse">
            <div class="panel-body">
                <?php echo htmlspecialchars($message->message); ?>
            </div>
        </div>
    </div>
<?php } ?>

<?php if ($messages_data[0]->type == 'single') { ?>
    <div class="clear">&nbsp;</div>
    <?php $session = $this->session->userdata('user_session'); ?>
    <script>
        //<![CDATA[
        $(document).ready(function() {
            function validateEditor() {
                $('#compose_message').bootstrapValidator('revalidateField', 'message');
            };
            
            $('#compose_message').bootstrapValidator({
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'fa fa-times',
                    validating: 'glyphicon glyphicon-refresh'
                },

                fields: {
                    'message': {
                        validators: {
                            callback: {
                                message: 'The message is required and cannot be empty',
                                callback: function(value, validator) {
                                    var code = $('[name="message"]').code();
                                    // <p><br></p> is code generated by Summernote for empty content
                                    return (code !== '' && code !== '<p><br></p>');
                                }
                            }
                        }
                    }
                }
            }).find('[name="message"]').summernote({
                height: 200,
                onkeyup: function() {
                    validateEditor();
                },
                onpaste: function() {
                    validateEditor();
                }
            });;
        });
        //]]>
    </script>
    <form role="form" action="<?php echo base_url() . 'message/reply/' . $to_reply_data->id; ?>" method="post" enctype="multipart/form-data" id="compose_message">
        <div class="col-sm-12">
            <div class="form-group">
                <textarea class="summernote-sm" name="message" data-bv-excluded="false"><?php echo set_value('message'); ?></textarea>
                <?php if (form_error('message') != '') { ?>
                    <label class="error"><?php echo form_error('message'); ?></label>
                <?php } ?>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" readonly>
                    <span class="input-group-btn">
                        <span class="btn btn-primary btn-file">
                            <?php echo $this->lang->line('browse_file'); ?><input type="file" multiple name="attachments">
                        </span>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" name="action" value="send" class="btn btn-success" data-toggle="tooltip" title="<?php echo $this->lang->line('send'), ' ', $this->lang->line('message'); ?>"><i class="fa fa-rocket"></i> <?php echo $this->lang->line('send'), ' ', $this->lang->line('message'); ?></button>
                <a href="<?php echo base_url() . 'message'; ?>" class="btn btn-danger" data-toggle="tooltip" title="<?php echo $this->lang->line('discard'); ?>"><?php echo $this->lang->line('discard'); ?></a>
            </div>
        </div>
    </form>
<?php } ?>